# Generated by Django 3.2.8 on 2021-10-26 11:28

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('first_name', models.CharField(blank=True, max_length=30, null=True)),
                ('last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('phone', models.CharField(max_length=10, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default=0, max_length=15)),
                ('avatar', models.ImageField(upload_to='avatar/%Y/%m')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shipper',
            fields=[
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='shipper_account', serialize=False, to='deliveryapp.user')),
                ('id_number', models.CharField(max_length=12, unique=True)),
                ('id_front_image', models.ImageField(upload_to='identity/%Y/%m')),
                ('id_back_image', models.ImageField(upload_to='identity/%Y/%m')),
            ],
        ),
        migrations.CreateModel(
            name='OrderPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('content', models.TextField(null=True)),
                ('ship_address', models.CharField(blank=True, max_length=250)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('is_checked', models.BooleanField(default=False)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ship_cost', models.DecimalField(decimal_places=2, max_digits=14)),
                ('is_winner', models.BooleanField()),
                ('active', models.BooleanField(null=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auctions', to='deliveryapp.orderpost')),
                ('shipper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipper_info', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['post'],
                'unique_together': {('post', 'shipper')},
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(null=True)),
                ('rate', models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(limit_value=5, message='Đánh giá 1-5'), django.core.validators.MinValueValidator(limit_value=1, message='Đánh giá 1-5')])),
                ('customer', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='customer_rating', to=settings.AUTH_USER_MODEL)),
                ('shipper', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='rating_shipper', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('customer', 'shipper')},
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('shipper', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='shipper_name', serialize=False, to='deliveryapp.user')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('ship_address', models.CharField(blank=True, max_length=250, null=True)),
                ('active', models.BooleanField(default=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'CHƯA GIAO HÀNG'), (1, 'ĐANG GIAO HÀNG'), (2, 'ĐÃ GIAO')], default=0)),
                ('pay_method', models.PositiveSmallIntegerField(choices=[(0, 'Zalo pay'), (1, 'Ví MOMO'), (2, 'TIỀN MẶT')], default=2)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='deliveryapp.auction')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_name', to=settings.AUTH_USER_MODEL)),
                ('service_cate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='deliveryapp.service')),
            ],
        ),
    ]
