# Generated by Django 3.2.8 on 2021-10-27 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryapp', '0004_order_product_cate'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='deliveryapp.order')),
                ('customer_received', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
