# Generated by Django 3.2.8 on 2021-11-02 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryapp', '0008_auto_20211102_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='active',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='auction',
            name='is_winner',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
