# Generated by Django 3.2.8 on 2021-11-02 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryapp', '0009_auto_20211102_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_shipper',
            field=models.BooleanField(default=False),
        ),
    ]
