# Generated by Django 3.2.8 on 2021-11-02 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryapp', '0012_alter_order_auction'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderpost',
            name='product_cate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='deliveryapp.productcategory'),
        ),
        migrations.AddField(
            model_name='orderpost',
            name='service_cate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='deliveryapp.service'),
        ),
    ]
