# Generated by Django 3.2.8 on 2021-11-04 01:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryapp', '0013_auto_20211102_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='choice',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(limit_value=2, message='Chọn nếu bạn là shipper'), django.core.validators.MinValueValidator(limit_value=1, message='Chọn nếu bạn là khách hàng')]),
        ),
    ]
