# Generated by Django 3.2.8 on 2021-11-08 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryapp', '0019_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipper',
            name='id_back_image',
            field=models.ImageField(upload_to='static/identity/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='shipper',
            name='id_front_image',
            field=models.ImageField(upload_to='static/identity/%Y/%m'),
        ),
    ]
