# Generated by Django 3.2.8 on 2021-11-10 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryapp', '0025_alter_auction_shipper'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auction',
            options={'ordering': ['post', 'created_date']},
        ),
        migrations.AlterModelOptions(
            name='orderpost',
            options={'ordering': ['created_date']},
        ),
        migrations.AlterModelOptions(
            name='rating',
            options={'ordering': ['created_date', 'updated_date']},
        ),
    ]
