# Generated by Django 3.2.8 on 2021-11-10 12:24

import deliveryapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryapp', '0028_auto_20211110_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=10, null=True, validators=[deliveryapp.models.validate_phone]),
        ),
    ]
