# Generated by Django 3.2.8 on 2021-11-10 14:08

import deliveryapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryapp', '0030_alter_shipper_id_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='phone',
            field=models.CharField(max_length=10, null=True, validators=[deliveryapp.models.validate_phone]),
        ),
        migrations.AlterField(
            model_name='orderpost',
            name='phone',
            field=models.CharField(max_length=10, null=True, validators=[deliveryapp.models.validate_phone]),
        ),
    ]
