# Generated by Django 3.2.8 on 2021-11-10 14:08

import deliveryapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryapp', '0031_auto_20211110_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='ship_cost',
            field=models.DecimalField(decimal_places=2, max_digits=14, validators=[deliveryapp.models.validate_number]),
        ),
    ]
