# Generated by Django 3.2.8 on 2021-11-10 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryapp', '0032_alter_auction_ship_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='ship_cost',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
    ]
