# Generated by Django 3.2.8 on 2021-11-10 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryapp', '0033_alter_auction_ship_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[(0, 'NAM'), (1, 'NỮ'), (2, 'KHÁC')], default=0, max_length=15),
        ),
    ]
